name: Daily News Agent

on:
  schedule:
    # Runs daily at 8:00 AM IST
    - cron: '30 2 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  send-daily-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run AI News Agent
      env:
        # Add your secrets here - these should match the secret names in GitHub
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        # Add any other environment variables your config needs
      run: |
        echo "Starting Daily News Agent at $(date)"
        python main.py
        echo "Daily News Agent completed at $(date)"
    
    - name: Upload logs (if job fails)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: news-agent-logs
        path: logs/
        retention-days: 7
